server {
    listen       80;
    server_name  localhost;

    # 开启密码验证
    auth_basic           "请输入密码访问我的游戏库";
    auth_basic_user_file /etc/nginx/.htpasswd; 

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # 允许显示目录列表 (如果你没有 index.html，想直接看文件列表的话可以开启下面这就话)
        # autoindex on;
    }
}
